---

- name: Check if deploy-args file exists
  local_action: stat path="{{ role_path }}/templates/deploy-args-{{ item.value.ubuntu_distribution |
    default(proxmox_vms_defaults.ubuntu_distribution) }}.j2"
  become: false
  with_dict: "{{ vms }}"
  register: deploy_file_exists

- name: Check if preseed file exists
  local_action: stat path="{{ role_path }}/files/ubuntu-{{ item.value.ubuntu_distribution |
    default(proxmox_vms_defaults.ubuntu_distribution) }}.seed"
  become: false
  with_dict: "{{ vms }}"
  register: preseed_file_exists

- name: Set distribution fact
  set_fact:
    distribution: "{{ item.0.value.ubuntu_distribution | default(proxmox_vms_defaults.ubuntu_distribution) }}"
  with_together:
    - "{{ lookup('dict', vms) }}"
    - "{{ deploy_file_exists.results }}"
  register: distributions_register

- name: Make a distribution list from distributions_register
  set_fact:
    distributions: "{{ distributions|default({}) | combine( {item.item.0.key: item.ansible_facts.distribution} ) }}"
  with_items: "{{ distributions_register.results }}"

- name: Create virtual machines
  proxmox_kvm:
    api_user: "{{ proxmox.api_user }}"
    api_password: "{{ proxmox.api_password }}"
    api_host: "{{ proxmox.api_host }}"
    node: "{{ item.0.value.node }}"
    name: "{{ item.0.key }}"
    net: "{{ item.0.value.net | default(proxmox_vms_defaults.net) }}"
    scsihw: "{{ item.0.value.scsihw | default(proxmox_vms_defaults.scsihw) }}"
    virtio: "{{ item.0.value.virtio | default(proxmox_vms_defaults.virtio) }}"
    cores: "{{ item.0.value.cores | default(proxmox_vms_defaults.cores) }}"
    memory: "{{ item.0.value.memory_size | default(proxmox_vms_defaults.memory_size) }}"
    balloon: "{{ item.0.value.balloon | default(proxmox_vms_defaults.balloon) }}"
    vga: "qxl"
    ostype: "{{ item.0.value.ostype | default(proxmox_vms_defaults.ostype) }}"
    # Look for deploy-args-file of the vm and replace all newlines with nothing. If not found take the
    # template-file and replace all newlines with nothing (all commands in one line). See ansible filter documentation.
    args: "{{ lookup('template', 'deploy-args-'~distributions[item.0.key]~'.j2'
              if item.1.stat.exists else proxmox_vms_defaults.deploy_args_template) |
              replace('\n', '') }}"
    cpu: "{{ item.0.value.cpu | default(proxmox_vms_defaults.cpu) }}"
    onboot: "{{ item.0.value.onboot | default(proxmox_vms_defaults.onboot) }}"
    state: present
  with_together:
    - "{{ lookup('dict', vms) }}"
    - "{{ deploy_file_exists.results }}"
  loop_control:
    pause: 10
  notify: sleep
  register: created_vms_pve

- meta: flush_handlers
  when: created_vms_pve.changed

- name: Create temporary directory for netboot image
  file:
    path: /tmp/{{ distributions[item.item.0.key] }}
    state: directory
    mode: 0755
  with_items: "{{ created_vms_pve.results }}"
  when: item.changed

- name: Download and unpack netboot image
  unarchive:
    src: http://archive.ubuntu.com/ubuntu/dists/{{ distributions[item.item.0.key] }}/main/installer-amd64/current/images/netboot/netboot.tar.gz
    dest: /tmp/{{ distributions[item.item.0.key] }}
    remote_src: yes
  with_items: "{{ created_vms_pve.results }}"
  when: item.changed

- name: Move linux kernel file
  copy:
    src: /tmp/{{ distributions[item.item.0.key] }}/ubuntu-installer/amd64/linux
    dest: /tmp/{{ distributions[item.item.0.key] }}-kernel
    remote_src: yes
  with_items: "{{ created_vms_pve.results }}"
  when: item.changed

- name: Create temporary directory for initrd
  file:
    path: /tmp/{{ distributions[item.item.0.key] }}/{{ item.item.0.key }}-initrd
    state: directory
    mode: 0755
  with_items: "{{ created_vms_pve.results }}"
  when: item.changed

- name: Unpack initrd
  shell: zcat /tmp/{{ distributions[item.item.0.key] }}/ubuntu-installer/amd64/initrd.gz | cpio -id
  args:
    chdir: /tmp/{{ distributions[item.item.0.key] }}/{{ item.item.0.key }}-initrd
  with_items: "{{ created_vms_pve.results }}"
  when: item.changed

- name: Copy preseed file
  copy:
    src: "{{ 'files/ubuntu-'~distributions[item.0.item.0.key]~'.seed' if item.1.stat.exists else proxmox_vms_defaults.preseed_template }}"
    dest: /tmp/{{distributions[item.0.item.0.key]}}/{{ item.0.item.0.key }}-initrd/preseed.cfg
  with_together:
    - "{{ created_vms_pve.results }}"
    - "{{ preseed_file_exists.results }}"
  when: item.0.changed

- name: Build post installation script
  template:
    src: templates/finish-installation.j2
    dest: /tmp/{{ distributions[item.item.0.key] }}/{{ item.item.0.key }}-initrd/finish-installation
  with_items: "{{ created_vms_pve.results }}"
  when: item.changed

- name: Repack initrd
  shell: find . | cpio --create --format='newc' | gzip > /tmp/{{ item.item.0.key }}-initrd.gz
  args:
    chdir: /tmp/{{ distributions[item.item.0.key] }}/{{ item.item.0.key }}-initrd
  with_items: "{{ created_vms_pve.results }}"
  when: item.changed

- name: Delete temporary directory
  file:
    state: absent
    path: /tmp/{{ distributions[item.item.0.key] }}
  with_items: "{{ created_vms_pve.results }}"
  when: item.changed

- name: Start ubuntu setup
  proxmox_kvm:
    api_user: "{{ proxmox.api_user }}"
    api_password: "{{ proxmox.api_password }}"
    api_host: "{{ proxmox.api_host }}"
    node: "{{ item.item.0.value.node }}"
    name: "{{ item.item.0.key }}"
    state: started
  with_items: "{{ created_vms_pve.results }}"
  notify: sleep
  when: item.changed

- meta: flush_handlers
  when: created_vms_pve.changed

- name: Run ubuntu setup only once
  proxmox_kvm:
    api_user: "{{ proxmox.api_user }}"
    api_password: "{{ proxmox.api_password }}"
    api_host: "{{ proxmox.api_host }}"
    node: "{{ item.item.0.value.node }}"
    name: "{{ item.item.0.key }}"
    delete: args
  with_items: "{{ created_vms_pve.results }}"
  when: item.changed

- name: Wait for virtual machines to finish installation
  proxmox_kvm:
    api_user: "{{ proxmox.api_user }}"
    api_password: "{{ proxmox.api_password }}"
    api_host: "{{ proxmox.api_host }}"
    node: "{{ item.item.0.value.node }}"
    name: "{{ item.item.0.key }}"
    state: current
  with_items: "{{ created_vms_pve.results }}"
  register: current_vm_state
  until: current_vm_state.status == "stopped"
  retries: 60
  delay: 10
  when: item.changed

- name: Restart vms
  proxmox_kvm:
    api_user: "{{ proxmox.api_user }}"
    api_password: "{{ proxmox.api_password }}"
    api_host: "{{ proxmox.api_host }}"
    node: "{{ item.item.0.value.node }}"
    name: "{{ item.item.0.key }}"
    state: started
  with_items: "{{ created_vms_pve.results }}"
  when: item.changed

- name: Wait for virtual machines to finish rebooting
  wait_for:
    port: 22
    host: "{{ item.item.0.value.network.ip }}"
    search_regex: OpenSSH
    delay: 10
    timeout: 480
    msg: Timeout or polling failed.
  when: item.changed
  with_items: "{{ created_vms_pve.results }}"

- name: Delete initrd
  file:
    state: absent
    path: /tmp/{{ item.item.0.key }}-initrd.gz
  with_items: "{{ created_vms_pve.results }}"
  when: item.changed

- name: Delete kernel
  file:
    state: absent
    path: /tmp/{{ distributions[item.item.0.key] }}-kernel
  with_items: "{{ created_vms_pve.results }}"
  when: item.changed

- name: Print success message
  debug:
    msg: "The installation of {{ distributions[item.item.0.key] }} on {{ item.item.0.key }} was successful!"
  when: item.changed
  with_items: "{{ created_vms_pve.results }}"
